language: python
dist: bionic
python:
    - 2.7
    - 3.7
env:
  global:
    PYTHONUNBUFFERED=yes
    LANGUAGE="en_US.UTF-8"
    LANG="en_US.UTF-8"
    LC_ALL="en_US.UTF-8"
    TERM="xterm-256color"
    LOCALE=C

before_install:
  - |
    python --version
    uname -a
    lsb_release -a
install:
  - # PyPy: we use -q here to avoid unicode errors in pip progress bar.
  - pip -q install -U pip
  - pip -q install -U tox
script:
  - tox -v -e $TRAVIS_PYTHON_VERSION -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
